Controllers/AboutUsController.cs
using EFS_23298_23327.Data;
using EFS_23298_23327.Models;
using EFS_23298_23327.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Xml.Linq;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace EFS_23298_23327.Controllers
{
   
    public class AboutUsController : Controller
    {
        private readonly UserManager<Utilizadores> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private Utilizadores userLogado { get; set; }


        public AboutUsController(
            UserManager<Utilizadores> userManager,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            
            return View();

        }


    }
}

Controllers/PerfilController.cs
using EFS_23298_23327.Data;
using EFS_23298_23327.Models;
using EFS_23298_23327.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Xml.Linq;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace EFS_23298_23327.Controllers
{
    [CustomAuthorize(Roles="Admin,Anfitriao,Cliente")]
    public class PerfilController : Controller
    {
        private readonly UserManager<Utilizadores> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private Utilizadores userLogado { get; set; }


        public PerfilController(
            UserManager<Utilizadores> userManager,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index( int? resId)
        {
            var user = await _context.Utilizadores.FindAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
            HashSet<string> roles = _userManager.GetRolesAsync(user).Result.ToHashSet();
            var vm = new UtilizadoresViewModel(user);
            vm.Roles = roles;
            TempData["ResId"] = resId;
            return View(vm);
            
        }

        public async Task<IActionResult> DadosPessoais()
        {
            var user = await _context.Utilizadores.FindAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
            HashSet<string> roles = _userManager.GetRolesAsync(user).Result.ToHashSet();
            var vm = new UtilizadoresViewModel(user);
            vm.Roles = roles;
            return PartialView("_PartialViewDadosP", vm);

        }

        public async Task<IActionResult> Reservas(int? resId)
        {
            var user = await _context.Utilizadores.FindAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var c = await _context.Clientes.Where(c => c.UserName.Equals(user.UserName)).FirstAsync();
            var r = await _context.Reservas.Where(r => r.Cliente.UserName.Equals(user.UserName)).ToListAsync();
            var vm = new Reservas(c);

            TempData["ResId"] = resId;
            return PartialView("_PartialViewReservas", r);

        }

        public async Task<IActionResult> Pref()
        {
            var user = await _context.Anfitrioes.FindAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
            HashSet<string> roles = _userManager.GetRolesAsync(user).Result.ToHashSet();
            var vm = new UserPrefs(user);
            return PartialView("_PartialViewPref", vm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPref(UserPrefs u)
        {
            if (u == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                
                u.UtilizadorId = u.UtilizadorId;

                TempData["PrefsAlterado"] = "Alterações guardadas com sucesso!";
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> VerReserva(int reservaId) {

            if(reservaId == null) {
                return NotFound();
            }

            var res =await _context.Reservas.Include(r => r.Cliente).Include(r => r.Sala).Include(r => r.ListaAnfitrioes).Where(r => (r.ReservaId == reservaId) && (r.Cliente.UserName == User.Identity.Name) && !r.Deleted).FirstOrDefaultAsync();

            if (res == null || res.Cliente.UserName != User.Identity.Name) {
                return NotFound();
            }


            return PartialView("_PartialVerReserva",res);

        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UtilizadoresViewModel userVM)
        {
            if (userVM == null)
            {
                return NotFound();
            }
            var user = await _context.Utilizadores.Where(m => m.Deleted == false).FirstOrDefaultAsync(m => m.Id == userVM.Id);
            if (user == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var user2 = await _context.Utilizadores.Where(u => u.Deleted == false).Where(u => u.UserName.Trim() == userVM.Username.Trim() && u.Id != userVM.Id).FirstOrDefaultAsync();

                if (userVM.Email != null && userVM.Email.Trim() != "")
                {
                    user2 = await _context.Utilizadores.Where(u => u.Deleted == false).Where(u => u.Email.Trim() == userVM.Email.Trim() && u.Id != userVM.Id).FirstOrDefaultAsync();
                    if (user2 != null)
                    {
                        ViewBag.UserExiste = "Utilizador com email \"<strong>" + user2.Email + "</strong>\" já existe!";
                        return RedirectToAction("Index");
                    }
                }                  

                //Se for cliente
                user.Email = userVM.Email;
                user.PrimeiroNome = userVM.PrimeiroNome;
                user.UltimoNome = userVM.UltimoNome;

                _context.Update(user);
                _context.Entry(user).Property(t => t.DataCriacao).IsModified = false;
                _context.Entry(user).Property(t => t.CriadoPorOid).IsModified = false;
                _context.Entry(user).Property(t => t.CriadoPorUsername).IsModified = false;
                await _context.SaveChangesAsync();                  
                ViewBag.ShowAlert = true;
                TempData["UtilizadorAlterado"] = "Alterações guardadas com sucesso!";
                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }
    }


    



}

Controllers/ReservasController.cs
using EFS_23298_23327.Data;
using EFS_23298_23327.Models;
using EFS_23298_23327.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace EFS_23298_23327.Controllers
{
    public class ReservasController : Controller
    {
        private readonly ApplicationDbContext _context;


       public ReservasController(ApplicationDbContext context) {
            _context = context;
        }

        [CustomAuthorize(Roles = "Anfitriao")]

        public async Task<IActionResult> Index() {
            var ud = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var u = await _context.Anfitrioes.Where(u => u.Id == ud).Include(u => u.userPrefsAn).ThenInclude(u => u.Cores).FirstOrDefaultAsync();
            TempData["userLoggedNome"] = u.PrimeiroNome + " " + u.UltimoNome;
            var r = await _context.Reservas.Include(c => c.Cliente).Include(a => a.Sala).Include(a => a.ListaAnfitrioes).Where(a => a.ListaAnfitrioes.Contains(u)).OrderBy(r => r.ReservaDate).ToListAsync();
            var vm = new ReservasDashboardViewModel(u.userPrefsAn, r);
            if (TempData["Save"] != null) {
                TempData["Save"] = TempData["Save"];

            }


            return View(vm);
        }


       

        [HttpPost]
        public async Task<IActionResult> SaveCor(Dictionary<string, string> dic, string showCancel) {

            var dik = dic;
            var ud = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var u = await _context.Anfitrioes.Where(u => u.Id == ud).Include(u => u.userPrefsAn).ThenInclude(u => u.Cores).FirstOrDefaultAsync();
            if (u.userPrefsAn == null) {
                var pref = new UserPrefsAnf();
                pref.AnfId = u.Id;
                pref.Anfitriao = u;
                u.userPrefsAn = pref;

            }
            var newListaCores = u.userPrefsAn.Cores;
            ;
            var corDict = new Dictionary<int, string>();

            var newDIct = new HashSet<UserPrefAnfCores>();


            foreach (var i in dic) {
                var cor = newListaCores.Where(c => c.Key == int.Parse(i.Key)).FirstOrDefault();
                if (cor != null) {
                    cor.Value = i.Value;
                    newDIct.Add(cor);
                } else {
                    UserPrefAnfCores c = new UserPrefAnfCores();
                    c.Key = int.Parse(i.Key);
                    c.Value = i.Value;
                    newDIct.Add(c);
                }

            }
            if (showCancel == "true") {
                u.userPrefsAn.mostrarCanceladas = true;
            } else {
                u.userPrefsAn.mostrarCanceladas = false;
            }

            u.userPrefsAn.Cores = newDIct;
            _context.Update(u);
            await _context.SaveChangesAsync();
            TempData["Save"] = "Preferências guardadas com sucesso!";

            return PartialView("_partialSave");

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Escape from Sellium</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href='https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css' rel='stylesheet' />
    <link rel="stylesheet" href="~/lib/multiselect/bootstrap-multiselect.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.min.js"
            integrity="sha256-sw0iNNXmOJbQhYFuC9OF2kOlD5KQKe1y5lfBn4C9Sjg="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css" />
    

    
   

    
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" asp-append-version="true" />
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link href="~/lib/fancybox/css/fancybox.css" rel="stylesheet" />
    <script src="~/lib/fancybox/js/fancybox.umd.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.20.0/jquery.validate.min.js"></script>

    <link rel="stylesheet" href="~/css/vapor.min.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.14/index.global.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/utf8/3.0.0/utf8.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.30.1/moment.min.js"></script>

    <link rel="stylesheet" href="~/EFS_23298_23327.styles.css" asp-append-version="true" />

</head>

<body class="h-100">
    <header>
        
       
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary" data-bs-theme="dark" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/imgs/logo-modified.png"
                         class="me-2"
                         height="50"
                         alt="MDB Logo"
                         loading="lazy" />
                   
                </a>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 text-white">
                        <li class="nav-item text-white">
                            <a class="nav-link text-white" asp-area="" asp-controller="AboutUs" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white"  asp-controller="TemasGeral" asp-area="" asp-action="Index">Themes</a>
                        </li>
                        @{
                            if ((User.Identity?.IsAuthenticated ?? false || User.IsInRole("Cliente"))  && (User.IsInRole("Admin") || User.IsInRole("Anfitriao"))) {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="Gerir" asp-controller="Temas" asp-action="Index">Manage</a>
                                </li>
                            }
                            if ((User.IsInRole("Anfitriao"))) {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Reservas" asp-action="Index">Reservations</a>
                                </li>
                            }

                        }
                        <li class="nav-item text-center mx-auto">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="text-decoration-none"><h1 class="text-center text-warning-emphasis">ESCAPE FROM SELLIUM</h1></a>
                        </li>
                       
                            @if(@User.Identity?.IsAuthenticated == false){
                            <li class="nav-item ms-auto me-2">
                                <a class="nav-link text-white ms-auto me-2" asp-area="" asp-controller="Account" asp-action="LogIn">Log in</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            }else{
                                <li class="nav-item ms-auto me-5">

                                <ul class="navbar-nav">
                                    <li class="nav-item dropdown">
                                        <button type="button" class="btn btn-danger rounded-circle dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                            @User.Identity.Name
                                        </button>
                                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDarkDropdownMenuLink">
                                            <li><a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Perfil">Profile</a></li>
                                            <li><hr class="dropdown-divider"></li>
                                            <li class="dropdown-item">
                                                <form class="form-inline" asp-area="" asp-action="Logout" asp-controller="Account" method="post">
                                                    <button type="submit" class="btn-outline-danger dropdown-item ">Logout</button>
                                                </form>
                                            </li>
                                            
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            }
                       
                       
                      
                        @{
                            if (User.Identity?.IsAuthenticated ?? false)
                            {
                               
                            }
                            
                        }
                     
                       
                    </ul>
                </div>
            </div>
            </nav>
      
    </header>
    <div id="testeTema"></div>
    @{
        @if (@TempData["Auth"] != null) {
            @if ((bool)@TempData["Auth"] == false) {
                <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
                    Erro! Não está autorizado!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }

        }
        @if (@TempData["ConfirmEmail"] != null) {
           
                <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
                @TempData["ConfirmEmail"]
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }

        }


    
    @if (@TempData["logOut"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
           Log out com sucesso!
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    @if (@TempData["NomeUtilizadorLogado"] != null && @TempData["NomeUtilizadorCriado"] == null) {
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
            Bem vindo <strong>@TempData["NomeUtilizadorLogado"]</strong>!
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    @if (@TempData["NomeUtilizadorCriado"] != null) {
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
            Registo efetuado com sucesso!
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <div class="container" style="min-width:90%;max-width:90%">
        <main role="main" class="pb-3 mt-2 vw-90">
            
            @RenderBody()
        </main>
    </div>
 
   

  
    
    <script src="~/lib/multiselect/bootstrap-multiselect.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        Fancybox.bind("[data-fancybox]", {
            // Your custom options
        });
    </script>


</body>
</html>