Models/Reservas.cs
using EFS_23298_23327.Data.Enum;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace EFS_23298_23327.Models
{
    public class Reservas : BaseEntity
    {
        /// <summary>
        /// Id da Reserva
        /// </summary>
        [Key]
        [DisplayName("Id")]
        public int ReservaId { get; set; }

        /// <summary>
        /// Data de inicio da Reserva
        /// </summary>
        [Display(Name = "Data de início reserva")]
        public DateTime ReservaDate { get; set; }

        /// <summary>
        /// Data do fim da Reserva
        /// </summary>
        [Display(Name = "Data de fim reserva")]
        public DateTime ReservaEndDate { get; set; }

        /// <summary>
        /// Número de pessoas da Reserva
        /// </summary>
        [Display(Name = "Número de pessoas")]
        [RegularExpression("^[1-9][0-9]{0,3}$", ErrorMessage ="Por favor insira um caracter de 1-9,opcionalmente seguido de,no máximo 3 caracteres de 1-9 ")]
        public int NumPessoas { get; set; }

        /// <summary>
        /// Preço Total da Reserva (preço do Tema * num Pessoas)
        /// </summary>
        [Display(Name = "Preço Total")]
        [DisplayFormat(DataFormatString = "{0:F1}", ApplyFormatInEditMode = true)]
        public decimal TotalPreco { get; set; }

        /// <summary>
        /// Lista de Anfitriões do Tema Reservado
        /// </summary>
        [DisplayName("Lista de Anfitriões")]
        public ICollection<Anfitrioes>? ListaAnfitrioes { get; set; }

        /// <summary>
        /// Id de quem faz a reserva (Cliente)
        /// </summary>
        [ForeignKey(nameof(Clientes))]
        [DisplayName("Id do Cliente")]
        public String? ClienteID { get; set; }

        /// <summary>
        /// Cliente que fez a reserva
        /// </summary>
        [DisplayName("Cliente")]
        public  Clientes? Cliente { get; set; }

        /// <summary>
        /// Id da Sala a que pertence o Tema Reservado
        /// </summary>
        [ForeignKey(nameof(Salas))]
        [DisplayName("Id da Sala")]
        public int SalaId { get; set; }

        /// <summary>
        /// Sala a que pertence o Tema Reservado
        /// </summary>
        [DisplayName("Sala")]
        public Salas Sala { get; set; }

        /// <summary>
        /// Boolean que define se a reserva está cancelada
        /// </summary>
        [DisplayName("Cancelada")]
        public bool Cancelada { get; set; }

        /// <summary>
        /// Nome do Tema reservado
        /// </summary>
        [DisplayName("Nome do Tema")]
        public String? TemaNome { get; set; }

        /// <summary>
        /// Dificuldade do Tema reservado
        /// </summary>
        [DisplayName("Dificuldade do Tema")]
        public Dificuldade? TemaDif { get; set; }

        /// <summary>
        /// Data em que a reserva foi cancelada
        /// </summary>
        [DisplayName("Data de Cancelamento")]
        public DateTime DataCancel {  get; set; }

        /// <summary>
        /// Construtor que recebe uma instância do Cliente que está a fazer a reserva
        /// </summary>
        /// <param name="u"></param>
        
        public Reservas(Clientes u) {
            this.ClienteID = u.Id;
            this.Cliente = u;
        }

        /// <summary>
        /// Construtor por defeito
        /// </summary>
        public Reservas() {
           
        }


    }
}

Controllers/ReservasController.cs
using EFS_23298_23327.Data;
using EFS_23298_23327.Models;
using EFS_23298_23327.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace EFS_23298_23327.Controllers
{
    public class ReservasController : Controller
    {
        private readonly ApplicationDbContext _context;


       public ReservasController(ApplicationDbContext context) {
            _context = context;
        }

        [CustomAuthorize(Roles = "Anfitriao")]

        public async Task<IActionResult> Index() {
            var ud = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var u = await _context.Anfitrioes.Where(u => u.Id == ud).Include(u => u.userPrefsAn).ThenInclude(u => u.Cores).FirstOrDefaultAsync();
            TempData["userLoggedNome"] = u.PrimeiroNome + " " + u.UltimoNome;
            var r = await _context.Reservas.Include(c => c.Cliente).Include(a => a.Sala).Include(a => a.ListaAnfitrioes).Where(a => a.ListaAnfitrioes.Contains(u)).OrderBy(r => r.ReservaDate).ToListAsync();
            var vm = new ReservasDashboardViewModel(u.userPrefsAn, r);
            if (TempData["Save"] != null) {
                TempData["Save"] = TempData["Save"];

            }


            return View(vm);
        }


       

        [HttpPost]
        public async Task<IActionResult> SaveCor(Dictionary<string, string> dic, string showCancel) {

            var dik = dic;
            var ud = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var u = await _context.Anfitrioes.Where(u => u.Id == ud).Include(u => u.userPrefsAn).ThenInclude(u => u.Cores).FirstOrDefaultAsync();
            if (u.userPrefsAn == null) {
                var pref = new UserPrefsAnf();
                pref.AnfId = u.Id;
                pref.Anfitriao = u;
                u.userPrefsAn = pref;

            }
            var newListaCores = u.userPrefsAn.Cores;
            ;
            var corDict = new Dictionary<int, string>();

            var newDIct = new HashSet<UserPrefAnfCores>();


            foreach (var i in dic) {
                var cor = newListaCores.Where(c => c.Key == int.Parse(i.Key)).FirstOrDefault();
                if (cor != null) {
                    cor.Value = i.Value;
                    newDIct.Add(cor);
                } else {
                    UserPrefAnfCores c = new UserPrefAnfCores();
                    c.Key = int.Parse(i.Key);
                    c.Value = i.Value;
                    newDIct.Add(c);
                }

            }
            if (showCancel == "true") {
                u.userPrefsAn.mostrarCanceladas = true;
            } else {
                u.userPrefsAn.mostrarCanceladas = false;
            }

            u.userPrefsAn.Cores = newDIct;
            _context.Update(u);
            await _context.SaveChangesAsync();
            TempData["Save"] = "Preferências guardadas com sucesso!";

            return PartialView("_partialSave");

        }
    }
}

Controllers/TemasGeralController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EFS_23298_23327.Data;
using EFS_23298_23327.Models;
using EFS_23298_23327.ViewModel;
using System.Security.Claims;
using Microsoft.AspNetCore.SignalR;
using EFS_23298_23327.Hubs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Antiforgery;
using Humanizer;
using System.Globalization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace EFS_23298_23327.Controllers
{
    [CustomAuthorize(Roles ="Cliente,Admin,Anfitriao")]
    public class TemasGeralController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHubContext<ClassHub> _progressHubContext;
        private readonly IEmailSender _emailSender;
        public TemasGeralController(ApplicationDbContext context, IHubContext<ClassHub> progressHubContext, IEmailSender emailSender)
        {
            _emailSender = emailSender;
            _progressHubContext = progressHubContext;
            _context = context;
        }

        // GET: TemasGeral
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            //Usado para testes ws
           // await _progressHubContext.Clients.All.SendAsync("tema", "system", "teste");

            var applicationDbContext = _context.Temas.Include(m => m.ListaFotos.Where(f => f.Deleted != true)).Where(m => m.Deleted != true).Where(t=>t.ListaFotos.Where(f=>!f.Deleted).Any()).Where(t=> t.SalaID!=null).OrderByDescending(m => m.DataCriacao);
            ICollection<TemasFotoViewModel> TmVm = new List<TemasFotoViewModel>();
            var lista = await applicationDbContext.ToListAsync();
            if (lista != null)
            {
                if (lista.Any())
                {
                    foreach (var tema in lista)
                    {
                        if (tema.ListaFotos.Any())
                        {
                            foreach (var foto in tema.ListaFotos)
                            {
                                TmVm.Add(new TemasFotoViewModel(tema.Nome, foto.Nome));
                            }
                        }

                    }
                }
            }
            return View(lista);
        }


   


     


        [AllowAnonymous]
        public async Task<IActionResult> Reserva(int? id) {

            if(id == null) {
                return NotFound();
            }

            var tema = await _context.Temas.Include(f => f.ListaFotos.Where(f => f.Deleted == false)).Include(s => s.Sala).ThenInclude(s => s.ListaReservas.Where(r=>!r.Cancelada || !r.Deleted)).ThenInclude(s => s.Cliente).Where(r => !r.Deleted).Where(s => s.SalaID == id).FirstOrDefaultAsync();
            if (tema == null) {
                return NotFound();
            }


           
            ReservaViewModel rvm = new ReservaViewModel(tema.Sala, tema);
            rvm.Sala.ListaReservas = rvm.Sala.ListaReservas.Where(r => !r.Cancelada).ToList();
            if (TempData["viewStart"] != null && TempData["viewEnd"] != null) {
                rvm.viewStart = (DateTime)TempData["viewStart"];
                rvm.viewEnd = (DateTime)TempData["viewEnd"];
            }

            return View(rvm);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Cancela(int resId) {


            var reserva = await _context.Reservas.Where(r => r.ReservaId == resId && !r.Deleted && !r.Cancelada && r.CriadoPorOid == User.FindFirstValue(ClaimTypes.NameIdentifier)).FirstOrDefaultAsync();

            if (reserva == null) {
                return Unauthorized();
            }

            var u = await _context.Clientes.FindAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (u == null) {
                TempData["ErroCliente"] = "Erro! Apenas clientes podem fazer reservas!";
                return RedirectToAction(nameof(Reserva), new { id = reserva.SalaId });

            }

            
            reserva.Cancelada = true;
            reserva.DataCancel = DateTime.Now;
            var callbackUrl = Url.Action(
                        "Index", "Perfil", values: new { area = "", resId = reserva.ReservaId }, protocol: HttpContext.Request.Scheme
                        );
            await _emailSender.SendEmailAsync(reserva.Cliente.Email, "Nova reserva criada!!",
          $"A sua reserva para o dia {reserva.ReservaDate} foi cancelada com sucesso! Clique no link para ver mais detalhes:\n{callbackUrl}");
            _context.Update(reserva);
            await _context.SaveChangesAsync();

            TempData["ReservaCancel"] = "Reserva <strong>" + reserva.ReservaId + "</strong> cancelada com sucesso!";
            return RedirectToAction(nameof(Reserva), new { id = reserva.SalaId });






        }


        [HttpPost]
        public async Task<IActionResult> ReservaData(DateTime dateI, int salaId, string viewType, DateTime viewStart, DateTime viewEnd) {
            if (User.Identity.IsAuthenticated==false) {
                ViewBag.erroUserAuth = true;
                return PartialView("_erroUserPartial");
            }

            var tema = await _context.Temas.Include(f => f.ListaFotos.Where(f => f.Deleted == false)).Include(s => s.Sala).ThenInclude(s => s.ListaReservas).ThenInclude(s => s.Cliente).Where(r => !r.Deleted).Where(s => s.SalaID == salaId).FirstOrDefaultAsync();


            if (tema == null) {
                return NotFound();
            }
            ReservaViewModel rvm = new ReservaViewModel(tema.Sala, tema);
            rvm.dataI = dateI;
            rvm.viewType = viewType;
            rvm.viewStart = viewStart;
            rvm.viewStart = viewEnd;



            return PartialView("_reservasModals", rvm);

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Reserva(int id,ReservaViewModel rvm) {

            if (User.Identity.IsAuthenticated == false) {
                ViewBag.erroUserAuth = true;
                return View(new RegisterViewModel());
            }

            Clientes u = null;

            u = await _context.Clientes.FindAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));

            if (u == null) {
                TempData["ErroCliente"] = "Erro! Apenas clientes podem fazer reservas!";
                return RedirectToAction(nameof(Reserva), rvm.Sala.SalaId);

            }

            var r = new Reservas(u);
            r.ListaAnfitrioes=rvm.Sala.ListaAnfitrioes;
            var tema = await _context.Temas.Include(s => s.Sala).Where(r => !r.Deleted).Where(s => s.SalaID == rvm.Sala.SalaId).FirstOrDefaultAsync();
            if (tema == null) {
                TempData["ErroCliente"] = "Erro! Não é possível reservar uma sala sem tema atribuído!";
                return RedirectToAction(nameof(Reserva), rvm.Sala.SalaId);

            }

            var endDate = rvm.dataI.AddMinutes(tema.TempoEstimado);
            var sala = await _context.Salas.Where(s=>s.SalaId==tema.SalaID).Include(s=>s.ListaAnfitrioes).FirstOrDefaultAsync();
            r.SalaId = sala.SalaId;
            r.NumPessoas = rvm.nPessoas;
            r.CriadoPorOid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            r.CriadoPorUsername = User.FindFirstValue(ClaimTypes.Name);
            r.DataCriacao = DateTime.Now;
            r.Sala = tema.Sala;
            r.ListaAnfitrioes = sala.ListaAnfitrioes;
            r.ReservaDate = rvm.dataI;
            var precoStr = (tema.Preco * rvm.nPessoas).ToString();
            r.TotalPreco = Convert.ToDecimal(precoStr.Replace('.', ','));
            r.TemaNome = tema.Nome;
            r.TemaDif = tema.Dificuldade;
            r.ReservaEndDate = endDate;
            tema.Sala.ListaReservas.Add(r);
            _context.Update(tema.Sala);
           
            await _context.SaveChangesAsync();

             var callbackUrl = Url.Action(
                        "Index", "Perfil", values: new { area = "", resId = r.ReservaId }, protocol: HttpContext.Request.Scheme
                        );
            await _emailSender.SendEmailAsync(r.Cliente.Email, "Nova reserva criada!",
          $"A sua reserva para o dia {r.ReservaDate} foi criada com sucesso! Clique no link para ver mais detalhes:\n{callbackUrl}");

            TempData["viewEnd"] = rvm.viewEnd;
            TempData["viewStart"] = rvm.viewStart;

            TempData["ReservaSucesso"] = "Reserva para " + r.ReservaDate.ToString("dd-MM-yyyy HH:mm:ss") + " efetuada com sucesso";
            await _progressHubContext.Clients.Group("Anfitrioes").SendAsync("reserva", "system", r.ReservaId + "," + @TimeSpan.FromHours((r.ReservaDate - DateTime.Now).TotalHours).Humanize() + "," + r.Sala.Numero);

            return RedirectToAction(nameof(Reserva),rvm.Sala.SalaId);






        }


   




    }
}

Views/TemasGeral/Index.cshtml
@model IEnumerable<EFS_23298_23327.Models.Temas>
@using EFS_23298_23327.Data

@{
    ViewData["Title"] = "Index";
    var i = 0;
}



    
        @if(!@Model.Any()){
            <div class="text-center mt-5 align-content-center">

                <span class="h2">No theme available! Please come back later</span>
            </div>
        }else{

    <table class="table">
        <tbody>


            @foreach (var item in Model) {
                String c = DifficultiesValue.GetDifficultyColor((int)item.Dificuldade);
                @if (i % 2 == 0) {
                    <tr class="border border-@c border-2 m-4">
                        <td style="width:50%; ">
                            <img class="d-block w-100" style="height:300px" src="/Imagens/@item.ListaFotos.First().Nome" alt="First slide" title="@item.Nome">
                        </td>
                        <td class="text-center">
                            <div class="h3 text-center text-@c mt-4">

                                @Html.DisplayFor(modelItem => item.Nome)

                            </div>
                            <div class="text-center text-info mt-4">
                                @Html.DisplayFor(modelItem => item.Descricao)
                            </div>
                            <div class="mt-4">
                                <a asp-action="Reserva" title="Ver" asp-route-id="@item.SalaID">
                                    <button type="button" class="btn btn-outline-@c ">VIEW THEME</button>
                                </a>
                            </div>

                        </td>
                    </tr>
                } else {
                    <tr class="border border-@c border-2 border">
                        <td class="text-center">
                            <div class="h3 text-center text-@c mt-4">
                                @Html.DisplayFor(modelItem => item.Nome)

                            </div>
                            <div class="text-center text-info mt-4">
                                @Html.DisplayFor(modelItem => item.Descricao)
                            </div>
                            <div class="mt-4">
                                <a asp-action="Reserva" title="Ver" asp-route-id="@item.SalaID">
                                    <button type="button" class="btn btn-outline-@c ">VIEW THEME</button>
                                </a>
                            </div>
                        </td>
                        <td style="width:50%">
                            <img class="d-block w-100" style="height:300px" src="/Imagens/@item.ListaFotos.First().Nome" alt="First slide" title="@item.Nome">
                        </td>
                    </tr>
                }
                i++;
            }
        </tbody>
        </table>
        }
       

Views/TemasGeral/_erroUserPartial.cshtml
<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
    Erro!Apenas utilizadores autenticados podem fazer reservas!
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Views/TemasGeral/_reservasModals.cshtml
@model EFS_23298_23327.ViewModel.ReservaViewModel

@{
    

   var precoTema = Model.Tema.Preco.ToString().Replace(",",".");

}
<script>
    $(document).ready(function () {
        console.log("@Model.viewStart");
        console.log("@Model.dataI");
        console.log("@Model.viewEnd");
        $("#nPessoas").on('input', function () {
            var preco = parseInt($(this).val()) * parseFloat((@precoTema));
            $("#preco").text(preco.toFixed(1))
        });
    });
   

    
</script>

   
    
<form asp-controller="TemasGeral" asp-action="Reserva" asp-route-id="@Model.Sala.SalaId" method="post">
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmar reserva para  @Model.dataI</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <div class="modal-body">
                    @Html.HiddenFor(m => m.Sala.SalaId)
                    @Html.HiddenFor(m => m.Tema.TemaId)
                    @Html.HiddenFor(m => m.viewEnd)
                    @Html.HiddenFor(m => m.viewType)
                    @Html.HiddenFor(m => m.viewStart)
                    @Html.HiddenFor(m => m.dataI)


                    <div class="input-group">
                        <span class="input-group-text">€
                            <span id="preco" class="input-group-text">@(@Model.Tema.MinPessoas * @Model.Tema.Preco)</span>

                        </span>
                        
                        <div class="form-floating">
                            <input type="number" class="form-control " id="nPessoas" min="@Model.Tema.MinPessoas" value="@Model.Tema.MinPessoas" asp-for="nPessoas" max="@Model.Tema.MaxPessoas">
                            <label for="nPessoas">@Html.LabelFor(m => m.nPessoas)</label>
                        </div>
                    </div>
                    
                        

                   
                
                </div>
                <div class="modal-footer">
                    
                    <button type="button" asp class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    <input type="submit" value="Confirmar Reserva" class="btn btn-success btn-lg" />
                </div>
               
            
        </div>
    </div>
</div>
</form>